[workspace]
name = "ros-jazzy-odrive-can"
channels = [
  "https://prefix.dev/robostack-jazzy",
  "https://prefix.dev/conda-forge",
]
platforms = [
  "linux-64",
  "linux-aarch64",
]
preview = ["pixi-build"]

[dependencies]
ros-jazzy-odrive-can = { path = "." }
ros-jazzy-ros2run = "*"
ros-jazzy-ros2launch = "*"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-rmw-fastrtps-cpp = "*"
ros-jazzy-rmw-zenoh-cpp = "*"

[package]
name = "ros-jazzy-odrive-can"
authors = ["Elian Neppel <neppel.elian.s6@dc.tohoku.ac.jp>"]

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build-dependencies]
setuptools = "*"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-rmw-fastrtps-cpp = "*"
ros-jazzy-rmw-zenoh-cpp = "*"
patchelf = "*"

[package.host-dependencies]
setuptools = "*"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-rmw-fastrtps-cpp = "*"
ros-jazzy-rmw-zenoh-cpp = "*"
patchelf = "*"

[package.build.config]
distro = "jazzy"

